import { Link } from 'wouter';
import { SEO } from '@/lib/seo';
import { useShop } from './cart';
import { ProductCard } from './catalogue';

export default function StockingHome() {
  const { products } = useShop();
  return <><SEO title="Bas pour femme : autofixants, voile et résille" canonical="/" description="La Maison des Dessous se consacre aux bas pour femme. Découvrez nos bas autofixants et pour porte-jarretelles. Livraison Pickup offerte."/>
    <main><section className="stocking-hero"><div><p className="stocking-eyebrow">LA MAISON DES DESSOUS</p><h1>L’élégance commence<br/>par un détail.</h1><p>Le voile sur la peau. Une dentelle bien choisie.<br/>Découvrez notre maison dédiée aux bas pour femme.</p><Link className="stocking-button" href="/boutique">Découvrir les bas →</Link><small>Livraison Pickup offerte en France métropolitaine</small></div><img src={products[0].images[0]} alt="Bas noirs à couture arrière et jarretière en dentelle" fetchPriority="high"/></section>
      <div className="stocking-ribbon"><span>Une boutique dédiée aux bas</span><span>Tailles sélectionnées au panier</span><span>Voile & résille</span></div>
      <section className="stocking-page"><p className="stocking-eyebrow">DEUX FAÇONS DE LES PORTER</p><h2 className="stocking-section-title">À chacune son maintien.</h2><div className="stocking-collections"><Link href="/bas-autofixants"><span>01</span><h3>Les autofixants</h3><p>Une jarretière siliconée, sans porte-jarretelles.</p><strong>Explorer la collection →</strong></Link><Link href="/bas-porte-jarretelles"><span>02</span><h3>Pour porte-jarretelles</h3><p>Le plaisir des attaches et des belles finitions.</p><strong>Explorer la collection →</strong></Link></div>
        <p className="stocking-eyebrow">LA SÉLECTION DE LA MAISON</p><h2 className="stocking-section-title">Voile, dentelle et résille.</h2><div className="stocking-grid">{products.slice(0,4).map(p=><ProductCard key={p.id} product={p}/>)}</div>
        <section className="stocking-guide-callout"><h2>Vos premiers bas ?</h2><p>Maintien, taille, transparence : quelques repères pour choisir.</p><Link href="/guide-des-bas">Lire le guide →</Link></section>
      </section></main></>;
}
export function Guide() {
  return <main className="stocking-page stocking-reading"><SEO title="Comment choisir ses bas pour femme" canonical="/guide-des-bas" description="Autofixants ou porte-jarretelles, taille et deniers : nos repères pour choisir vos bas."/><p className="stocking-eyebrow">LES CONSEILS DE LA MAISON</p><h1>Bien choisir ses bas.</h1><h2>Autofixants ou porte-jarretelles ?</h2><p>Les autofixants tiennent grâce à une bande de silicone à l’intérieur de la jarretière. Les bas non autofixants se fixent aux attaches d’un porte-jarretelles. Vérifiez toujours le maintien indiqué sur la fiche : la dentelle seule ne permet pas de le deviner.</p><Link href="/bas-autofixants">Découvrir les autofixants →</Link><h2>Choisir la taille</h2><p>Les tailles changent selon la marque. Une taille unique ne convient pas à toutes les morphologies. Si vous hésitez, contactez-nous avec la référence, votre taille en centimètres et vos mesures : nous vérifierons le tableau du fabricant avant votre achat.</p><h2>Comprendre les deniers</h2><p>Le denier mesure la masse du fil. Pour un voile, une valeur faible correspond généralement à un rendu plus fin et transparent. Le rendu dépend aussi du tissage et de la couleur. La résille se distingue par sa maille ajourée.</p><h2>Les enfiler avec soin</h2><p>Retirez vos bijoux, rassemblez délicatement le bas, placez la pointe puis déroulez sur la jambe. Évitez de tirer uniquement sur la jarretière. Suivez l’étiquette pour l’entretien.</p><Link href="/bas-porte-jarretelles">Découvrir les bas pour porte-jarretelles →</Link></main>;
}
